import os
import logging
from datetime import datetime


class CapabilityImprover:

    def __init__(self, capability_engine, plugins_path="plugins"):

        self.logger = logging.getLogger("Orion")

        self.capability_engine = capability_engine

        self.plugins_path = plugins_path

    # ------------------------------------------------
    # Improve capability
    # ------------------------------------------------
    def improve(self, capability_name, reason="performance"):

        self.logger.info(
            f"🧠 Improving capability: {capability_name} ({reason})"
        )

        try:

            new_name = f"{capability_name}_v2"

            success = self._create_improved_capability(
                capability_name,
                new_name
            )

            if success:

                self.capability_engine.reload_capabilities()

                self.logger.info(
                    f"🚀 Improved capability installed: {new_name}"
                )

                return new_name

        except Exception as e:

            self.logger.error(
                f"Capability improvement failed: {e}"
            )

        return None

    # ------------------------------------------------
    # Create improved plugin
    # ------------------------------------------------
    def _create_improved_capability(self, old_name, new_name):

        filename = f"{new_name}.py"

        filepath = os.path.join(self.plugins_path, filename)

        if os.path.exists(filepath):

            return True

        try:

            class_name = self._class_name(new_name)

            code = self._generate_improved_code(
                class_name,
                old_name
            )

            with open(filepath, "w") as f:
                f.write(code)

            self.logger.info(
                f"📦 Improved capability created: {filename}"
            )

            return True

        except Exception as e:

            self.logger.error(
                f"Failed generating improved capability: {e}"
            )

            return False

    # ------------------------------------------------
    # Convert name to class format
    # ------------------------------------------------
    def _class_name(self, name):

        parts = name.split("_")

        return "".join(p.capitalize() for p in parts)

    # ------------------------------------------------
    # Generate improved code template
    # ------------------------------------------------
    def _generate_improved_code(self, class_name, base_capability):

        timestamp = datetime.utcnow().isoformat()

        template = f'''
"""
Auto-improved capability

Original capability: {base_capability}
Generated by Orion Self-Improvement System
Timestamp: {timestamp}
"""


class {class_name}:

    def __init__(self):

        self.name = "{class_name}"
        self.base_capability = "{base_capability}"

    def execute(self, state):

        data = state.get("data", {{}})

        # Improved processing simulation
        processed = {{
            "optimized": True,
            "original_capability": self.base_capability,
            "data_size": len(str(data))
        }}

        state["last_capability"] = self.name
        state["optimization"] = processed

        return state
'''

        return template.strip()