import os
import json
import logging


class PipelineRegistry:
    """
    Pipeline Registry for Orion.

    Responsible for storing, loading and managing
    automation pipelines generated by the system.
    """

    def __init__(self, pipelines_path="pipelines"):

        self.logger = logging.getLogger("Orion")

        self.pipelines_path = pipelines_path

        self._ensure_pipeline_folder()

    # ------------------------------------------------
    # Ensure pipelines directory exists
    # ------------------------------------------------
    def _ensure_pipeline_folder(self):

        if not os.path.exists(self.pipelines_path):

            os.makedirs(self.pipelines_path)

            self.logger.info(
                f"📁 Created pipelines directory: {self.pipelines_path}"
            )

    # ------------------------------------------------
    # Save pipeline
    # ------------------------------------------------
    def save_pipeline(self, name, pipeline):

        path = os.path.join(
            self.pipelines_path,
            f"{name}.json"
        )

        try:

            with open(path, "w", encoding="utf-8") as f:

                json.dump(pipeline, f, indent=4)

            self.logger.info(
                f"💾 Pipeline saved: {name}"
            )

        except Exception as e:

            self.logger.error(
                f"❌ Failed saving pipeline {name}: {e}"
            )

    # ------------------------------------------------
    # Load pipeline
    # ------------------------------------------------
    def load_pipeline(self, name):

        path = os.path.join(
            self.pipelines_path,
            f"{name}.json"
        )

        if not os.path.exists(path):

            self.logger.warning(
                f"⚠️ Pipeline not found: {name}"
            )

            return None

        try:

            with open(path, "r", encoding="utf-8") as f:

                pipeline = json.load(f)

            self.logger.info(
                f"📂 Pipeline loaded: {name}"
            )

            return pipeline

        except Exception as e:

            self.logger.error(
                f"❌ Failed loading pipeline {name}: {e}"
            )

            return None

    # ------------------------------------------------
    # Check if pipeline exists
    # ------------------------------------------------
    def pipeline_exists(self, name):

        path = os.path.join(
            self.pipelines_path,
            f"{name}.json"
        )

        return os.path.exists(path)

    # ------------------------------------------------
    # List pipelines
    # ------------------------------------------------
    def list_pipelines(self):

        pipelines = []

        for filename in os.listdir(self.pipelines_path):

            if filename.endswith(".json"):

                pipelines.append(
                    filename.replace(".json", "")
                )

        return pipelines

    # ------------------------------------------------
    # Delete pipeline
    # ------------------------------------------------
    def delete_pipeline(self, name):

        path = os.path.join(
            self.pipelines_path,
            f"{name}.json"
        )

        if not os.path.exists(path):

            self.logger.warning(
                f"⚠️ Pipeline not found: {name}"
            )

            return False

        try:

            os.remove(path)

            self.logger.info(
                f"🗑️ Pipeline deleted: {name}"
            )

            return True

        except Exception as e:

            self.logger.error(
                f"❌ Failed deleting pipeline {name}: {e}"
            )

            return False